apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
       feature: exec
  template:
    metadata:
       labels:
         feature: exec
    spec:
      containers:
      - name: agnhost
        image: uhub.service.ucloud.cn/testuk8s/agnhost:2.2
