{{$PROMETHEUS_SCRAPE_KUBELETS := DefaultParam .PROMETHEUS_SCRAPE_KUBELETS false}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.46.0
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.46.0
    spec:
      containers:
      - args:
        {{if $PROMETHEUS_SCRAPE_KUBELETS}}
        - --kubelet-service=kube-system/kubelet
        {{end}}
        - --prometheus-config-reloader=uhub.service.ucloud.cn/testuk8s/prometheus-config-reloader:v0.46.0
        - --secret-field-selector=type=prometheus-alert
        image: uhub.service.ucloud.cn/testuk8s/prometheus-operator:v0.46.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: {{IfThenElse (lt .Nodes 500) 200 400}}Mi
          requests:
            cpu: 200m
            memory: {{IfThenElse (lt .Nodes 500) 200 400}}Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
