apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netperf
  name: worker
  labels:
    group: network
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        group: network
        name: worker
    spec:
      containers:
      - image: uhub.service.ucloud.cn/testuk8s/netperfbenchmark:0.1
        name: worker
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "500m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

